### ISSUE TITLE
ReactLoadableSSRAddon is not a constructor

### ISSUE THREAD

**Issue by tatchi** [themgoncalves/react-loadable-ssr-addon#1]
# ReactLoadableSSRAddon is not a constructor

I get an error while I try to import ReactLoadableSSRAddon 

`const ReactLoadableSSRAddon = require('react-loadable-ssr-addon')`

## Expected Behavior

No errors.

## Current Behavior

Get the following error

> ReactLoadableSSRAddon is not a constructor
## Possible Solution

To make it work, I need to import it like that:

`const ReactLoadableSSRAddon = require('react-loadable-ssr-addon').default`

**Comment by themgoncalves** [comment]
@tatchi thanks for reporting, we will release a fix for that today.

**Comment by themgoncalves** [comment]
@tatchi fix for this issue was release in the `v0.1.1`.

**Comment by tatchi** [comment]
@themgoncalves  Yes I confirm it works 👍  Thanks  :)
