### ISSUE TITLE
Writing JSON to memory instead of disk

### ISSUE THREAD

**Issue by Schachte** [themgoncalves/react-loadable-ssr-addon#19]
# Issue Title
I'm looking to read the manifest out of memory instead of disk for the instance of running our system via the webpack dev server instead of our production bundles. 

## Expected Behavior
Conditionally read in manifest via in-memory file system when running dev env. 

## Current Behavior
Looks like I'm only always writing the manifest to disk

**Comment by Schachte** [comment]
I made a PR on a fork to support this, but didn't update tests yet. 
https://github.com/connexta/react-loadable-ssr-addon/pull/1

**Comment by themgoncalves** [comment]
Closing this issue as couldn't spot relevance or feasibility for the time being
