### ISSUE TITLE
Docs may have module order the wrong way round

### ISSUE THREAD

**Issue by tomkelsey** [themgoncalves/react-loadable-ssr-addon#6]
Me again 😅

The readme provides this as an example:

`const modulesToBeLoaded = [...manifest.entrypoints, ...Array.from(modules)];`

If you have the entrypoints/main bundle first then I believe this causes the chunks to be fetched twice - once initiated by the source html and then again initiated by the main bundle.

Alternatively, if you have them the other way round, the chunks are loaded first and once it gets to the main bundle they'll already be loaded and so the bundle won't instigate another request for the chunks.

`const modulesToBeLoaded = [..Array.from(modules), ...manifest.entrypoints];`

**Comment by themgoncalves** [comment]
Hey @tomkelsey do you have any example of this? Also if you have a screenshot from the `Network tab` from the `console developer tools` would be very helpful.

So far I've tested it with the current `built-in` example and seems like this issue might be relative.
In the `built-in` example, the `entry point file` is lightweight, by which the loading occurs synchronously and in the correct order.

Although when I inverted the its order as suggested by you, the reported behaviour started to happens, which means that this **might be related to the file weigh**t.

**Comment by tomkelsey** [comment]
That's interesting!

So I have just tried to re-create it with the built in example and was seeing the same as you:

As per the readme:

`const modulesToBeLoaded = [...manifest.entrypoints, ...Array.from(modules)];`

Works properly.

And if you switch them around to what works in my environment:

`const modulesToBeLoaded = [...manifest.entrypoints, ...Array.from(modules)];`

They are then loaded twice.

🤔

It could well be related to file weight. Of potential interest is that if you upgrade the example project to webpack 4:

`npm install webpack@4 webpack-cli`

And run the example again, it doesn't seem to make a difference which way round they are for the example project.

My own project is running webpack 4 but the order definitely makes a difference there so must be file weight or some other variable / webpack config causing it.

I haven't so far been able to recreate what I'm experiencing in my environment via a small example.

**Comment by themgoncalves** [comment]
Thanks for that observation @tomkelsey!

But sadly we can upgrade the framework to Webpack v4+, we are still using Webpack 3 to ensure that we maintain the compatibility with both versions 😄
