### ISSUE TITLE
Can't resolve './dist/assets-manifest.json'

### ISSUE THREAD

**Issue by devarwr** [themgoncalves/react-loadable-ssr-addon#9]
When I run a build with a clean dist directory, the build fails saying that it cannot resolve the manifest file. Even though the build fails, I see the manifest file generated in the correct directory. I wonder if manifest file is getting generated by webpack after the build attempts to compile the server file that imports it? 

Error: "ERROR in ./app.js
    Module not found: Error: Can't resolve './dist/assets-manifest.json'"

webpack:
```js
plugins: [
            new webpack.DefinePlugin({
                'process.env': {
                    NODE_ENV: JSON.stringify('production')
                }
            }),
            new CleanWebpackPlugin(),
            new OptimizeCssAssetsPlugin(),
            new MiniCssExtractPlugin({
                filename: '[name].css',
            }),
            new webpack.optimize.OccurrenceOrderPlugin(),
            new ReactLoadablePlugin({
                filename:  path.resolve(__dirname, 'dist', 'manifest.json'),
            }),
            new ReactLoadableSSRAddon({
                filename:  path.resolve(__dirname, 'dist', 'assets-manifest.json'),
            }),
```

server:
```js
return Promise.all(promises).then(() => {
                loadOnServer({ store, location, Routes })
                    .then(() => {
                        let context = {};
                        let appHTML = renderToString(
                            <Loadable.Capture report={moduleName => modules.add(moduleName)}>
                                <Provider store={store} key="provider">
                                    <StaticRouter location={location} context={context}>
                                        <ReduxAsyncConnect routes={Routes} />
                                    </StaticRouter>
                                </Provider>
                            </Loadable.Capture>
                        );
                        const helmet = Helmet.renderStatic();
                        const { getBundles } = require('react-loadable-ssr-addon');
                        const manifest = require('./dist/assets-manifest.json');
```

**Comment by themgoncalves** [comment]
Hi @devarwr 

I see that the issue are being thrown by `app.js` and I guess it is not your `server module`, is that right? If so, is there any particular reason why are you loading the `assets manifest` in the client?

### Understanding the issue

`Webpack` as an assets manager, processes your application and builds a dependency graph which maps every module needed in your application. Therefore, if you are **trying to load a non existent file** it will throw an `Module not found` error, which is precisely what you are getting.

Besides that, the `assets manifest` is generated by `react-loadable-ssr-addon` plugin, meaning that it will only exists after your application is build and not before.

That is the reason why we use that only in the `server side` through `required()` method and not by `import` method.

### Suggested solutions

If I got the correct understanding of you application set-up, you have 2 ways to get it done:

1) Don't delete the `assets-manifests` during the `clean-up`;
2) Or simply don't use that in the client 😛


### Further infos

Feel free to give extra feedback and infos about your situation.

**Comment by devarwr** [comment]
@themgoncalves - thank you for your response. The app.js file is my server file. I’m trying cleaning out the dist directory as part of the build because I found that the getbundles function was reading bundles from the prior build’s asset-manifest.json file, which caused my site to try to load chunkhashed bundles that didn’t exist.

**Comment by themgoncalves** [comment]
@devarwr Ok, so we can avoid that issue by doing a file checking:

```js
// utils/getApplicationBundle.js

import fs from 'fs';
import { getBundles } from 'react-loadable-ssr-addon';

export default function getApplicationBundle(modules) {
  const manifestPath = `./dist/assets-manifest.json`;

  if (!fs.existsSync(manifestPath)) {
    return {
      styles: [],
      scripts: [],
    };
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const bundles = getBundles(manifest, [...manifest.entrypoints, ...modules]);

  const styles = bundles.css || [];
  const scripts = bundles.js || [];

  return {
    styles,
    scripts,
  };
}
```

**Comment by devarwr** [comment]
@themgoncalves That did the trick! Many thanks for your assistance.

**Comment by endiliey** [comment]
My issue is kinda similar. 

I have a webpack build process, and it is has two isolated configurations (one for my server-side build, and another for my client-side build). Here's an incredibly simplified example:

// webpack.config.js
```js
// webpack.config.js
const { ReactLoadablePlugin } = require('react-loadable-ssr-addon')

const clientConfig = {
  entry: './src/client/index.js',
  plugins: [
    // This plugin creates the react-loadable.json file
    new ReactLoadablePlugin({
      filename: path.resolve(__dirname, 'react-loadable.json')
    }),
  ]
}

const serverConfig = {
  // This entry point makes use of the built react-loadable.json file
  entry: './src/server/index.js'
}

module.exports = [clientConfig, serverConfig]
```

If the file exists before the build runs, then everything flows smoothly, so the question became how to make it work without the pre-existence of that artifact.
If the file does not exist before the build run, I find this "Can't resolve blablabla error". 

Any good idea to solve this ?
I am considering to simply poll for the existence of the required file with some webpack plugin...
